#!/usr/bin/env node
import fs from 'fs'

const file = fs.readFileSync('./reporter.json');
const names = JSON.parse(file).data;

const paths = names.map(({name, chars}) => ({ 

       url: `https://chinese-fonts-cdn.deno.dev/chinesefonts3/packages/ysyrxk/dist/slideyouran-Regular2_0/${name}`,
       unicodeRange: chars
}));

console.log(`const fonts = ${JSON.stringify(paths)}`)
